#!/usr/bin/env python3
import argparse
import csv
import shutil
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any, List, Set


def normalize_track_id(value: Any) -> str:
    s = str(value or "").strip()
    if not s:
        return ""
    if "spotify.com/track/" in s:
        s = s.split("spotify.com/track/", 1)[1].split("?", 1)[0].split("/", 1)[0]
    if s.startswith("spotify:track:"):
        s = s.split("spotify:track:", 1)[1]
    return s.strip()


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Delete tracks from music-library DB using an approved review CSV (your_decision=yes).",
    )
    parser.add_argument(
        "--csv",
        required=True,
        help="Path to review CSV generated by build_music_library_removal_review.py",
    )
    parser.add_argument(
        "--db",
        default=str(repo_root / "data" / "music-library" / "spotify_music_library.db"),
        help="Path to spotify_music_library.db",
    )
    parser.add_argument(
        "--decision-column",
        default="your_decision",
        help="CSV column containing yes/no approval values.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually delete rows. If omitted, runs in dry-run mode.",
    )
    parser.add_argument(
        "--backup",
        action="store_true",
        help="Create a timestamped .bak copy in backups/ before deleting (only with --apply).",
    )
    parser.add_argument(
        "--preview-limit",
        type=int,
        default=10,
        help="How many approved rows to preview in output.",
    )
    return parser.parse_args()


def is_yes(value: str) -> bool:
    v = (value or "").strip().lower()
    return v in {"yes", "y", "true", "1"}


def main() -> None:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    csv_path = Path(args.csv).expanduser().resolve()
    db_path = Path(args.db).expanduser().resolve()

    if not csv_path.exists():
        raise FileNotFoundError(f"Review CSV not found: {csv_path}")
    if not db_path.exists():
        raise FileNotFoundError(f"Music-library DB not found: {db_path}")

    requested_yes_ids: Set[str] = set()
    skipped_not_eligible = 0
    skipped_not_in_db = 0
    skipped_missing_id = 0
    rows_total = 0

    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            raise ValueError("CSV has no header row")

        headers = {h.strip() for h in reader.fieldnames if h}
        if "track_id" not in headers:
            raise ValueError("CSV must include 'track_id' column")
        if args.decision_column not in headers:
            raise ValueError(f"CSV must include decision column '{args.decision_column}'")

        for row in reader:
            rows_total += 1
            track_id = normalize_track_id(row.get("track_id"))
            if not track_id:
                skipped_missing_id += 1
                continue

            if not is_yes(str(row.get(args.decision_column) or "")):
                continue

            eligible_value = str(row.get("eligible_for_delete") or "yes")
            in_db_value = str(row.get("in_music_library_db") or "yes")
            if not is_yes(eligible_value):
                skipped_not_eligible += 1
                continue
            if not is_yes(in_db_value):
                skipped_not_in_db += 1
                continue

            requested_yes_ids.add(track_id)

    con = sqlite3.connect(str(db_path))
    try:
        cur = con.cursor()
        cur.execute('SELECT rowid, "Track_ID" FROM tracks ORDER BY rowid ASC')
        raw_rows: List[tuple[int, str]] = [(int(r[0]), str(r[1] or "").strip()) for r in cur.fetchall()]

        matched_by_track_id: dict[str, tuple[int, str]] = {}
        for rowid, raw_track_id in raw_rows:
            normalized = normalize_track_id(raw_track_id)
            if normalized not in requested_yes_ids:
                continue
            if normalized not in matched_by_track_id:
                matched_by_track_id[normalized] = (rowid, raw_track_id)

        matched_rows: List[tuple[int, str]] = list(matched_by_track_id.values())

        print(f"Review CSV: {csv_path}")
        print(f"Music DB: {db_path}")
        print(f"Rows in review CSV: {rows_total}")
        print(f"Approved yes IDs in CSV: {len(requested_yes_ids)}")
        print(f"Skipped approved but not eligible: {skipped_not_eligible}")
        print(f"Skipped approved but not in DB: {skipped_not_in_db}")
        print(f"Skipped missing track_id: {skipped_missing_id}")
        print(f"Rows in tracks table: {len(raw_rows)}")
        print(f"Approved IDs found in DB: {len(matched_rows)}")
        print(f"Rows selected for delete (one per Track_ID): {len(matched_rows)}")

        if matched_rows:
            preview = matched_rows[: max(0, args.preview_limit)]
            print("Example rows to delete:")
            for rowid, track_id in preview:
                print(f"  - rowid={rowid} Track_ID={track_id}")
            if len(matched_rows) > len(preview):
                print(f"  ... +{len(matched_rows) - len(preview)} more")

        if not args.apply:
            print("\nDry-run complete. Re-run with --apply to delete.")
            return

        if args.backup:
            ts = datetime.now().strftime("%Y%m%d-%H%M%S")
            backup_dir = repo_root / "backups"
            backup_dir.mkdir(parents=True, exist_ok=True)
            backup_path = backup_dir / f"{db_path.name}.{ts}.bak"
            shutil.copy2(db_path, backup_path)
            print(f"Backup created: {backup_path}")

        cur.executemany("DELETE FROM tracks WHERE rowid = ?", [(rowid,) for rowid, _track_id in matched_rows])
        con.commit()
        print(f"\nDeleted {len(matched_rows)} row(s) from tracks.")
    finally:
        con.close()


if __name__ == "__main__":
    main()
